apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-adb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-adb
  template:
    metadata:
      labels:
        app: hello-adb
    spec:
      containers:
        - name: python-hello-adb
          image: hello-adb:1.0
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "64Mi"
              cpu: "100m"